# Generated by Django 5.0.3 on 2024-04-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0004_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Paid')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='bus',
            name='seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bus',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='1', max_length=2),
        ),
    ]
