# Generated by Django 5.0.4 on 2024-04-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0008_bus_isdaily'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='viaManyToMany',
            field=models.ManyToManyField(to='reservationApp.location'),
        ),
    ]
