# Generated by Django 5.0.4 on 2024-04-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0009_schedule_viamanytomany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='viaManyToMany',
            new_name='via',
        ),
    ]
