# Generated by Django 5.0.4 on 2024-04-30 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0010_rename_viamanytomany_schedule_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.TimeField(default=datetime.time),
        ),
    ]
