# Generated by Django 5.0.4 on 2024-04-30 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0011_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.IntegerField(default=datetime.time),
        ),
    ]
