# Generated by Django 5.0.4 on 2024-04-30 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0013_alter_schedule_time_seats_booking_book_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='book_seats',
        ),
        migrations.DeleteModel(
            name='Seats',
        ),
    ]
