# Generated by Django 5.0.4 on 2024-04-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0016_seats_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
