# Generated by Django 5.0.4 on 2024-04-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0017_seats_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.IntegerField(default=0),
        ),
    ]
