# Generated by Django 5.0.4 on 2024-05-01 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0019_booking_fare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='time',
        ),
    ]
